//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.09 at 11:05:44 AM CST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AggregateGenBusEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AggregateGenBusEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="STATION_POWER"/>
 *     &lt;enumeration value="ETC_TOR"/>
 *     &lt;enumeration value="DEMAND_RESPONSE"/>
 *     &lt;enumeration value="ParticipateLoad"/>
 *     &lt;enumeration value="DEFAULT_LAP"/>
 *     &lt;enumeration value="SUBLAP"/>
 *     &lt;enumeration value="TH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AggregateGenBusEnumType", namespace = "http://www.interpss.org/Schema/odm/2008")
@XmlEnum
public enum AggregateGenBusEnumType {

    STATION_POWER("STATION_POWER"),
    ETC_TOR("ETC_TOR"),
    DEMAND_RESPONSE("DEMAND_RESPONSE"),
    @XmlEnumValue("ParticipateLoad")
    PARTICIPATE_LOAD("ParticipateLoad"),
    DEFAULT_LAP("DEFAULT_LAP"),
    SUBLAP("SUBLAP"),
    TH("TH");
    private final String value;

    AggregateGenBusEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AggregateGenBusEnumType fromValue(String v) {
        for (AggregateGenBusEnumType c: AggregateGenBusEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
