//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.09 at 11:05:44 AM CST 
//


package org.ieee.odm.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Data structure for defining Aclf based contingency analysis for the study case
 * 		
 * 
 * <p>Java class for ContingencyAnalysisXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContingencyAnalysisXmlType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}BaseAnalysisTypeXmlType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.interpss.org/Schema/odm/2008}ContingencyAnalysisEnumType"/>
 *         &lt;element name="defaultAclfAlgorithm" type="{http://www.ieee.org/odm/Schema/2008}AclfAlgorithmXmlType" minOccurs="0"/>
 *         &lt;element name="option" type="{http://www.interpss.org/Schema/odm/2008}ContingencyOptionXmlType" minOccurs="0"/>
 *         &lt;element name="limitRunCases" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="maxRunCases" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="aclfAnalysisCase" type="{http://www.interpss.org/Schema/odm/2008}AclfAnalysisCaseXmlType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContingencyAnalysisXmlType", namespace = "http://www.interpss.org/Schema/odm/2008", propOrder = {
    "type",
    "defaultAclfAlgorithm",
    "option",
    "limitRunCases",
    "maxRunCases",
    "aclfAnalysisCase"
})
public class ContingencyAnalysisXmlType
    extends BaseAnalysisTypeXmlType
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ContingencyAnalysisEnumType type;
    protected AclfAlgorithmXmlType defaultAclfAlgorithm;
    protected ContingencyOptionXmlType option;
    protected Boolean limitRunCases;
    protected Integer maxRunCases;
    protected List<AclfAnalysisCaseXmlType> aclfAnalysisCase;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ContingencyAnalysisEnumType }
     *     
     */
    public ContingencyAnalysisEnumType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContingencyAnalysisEnumType }
     *     
     */
    public void setType(ContingencyAnalysisEnumType value) {
        this.type = value;
    }

    /**
     * Gets the value of the defaultAclfAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link AclfAlgorithmXmlType }
     *     
     */
    public AclfAlgorithmXmlType getDefaultAclfAlgorithm() {
        return defaultAclfAlgorithm;
    }

    /**
     * Sets the value of the defaultAclfAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link AclfAlgorithmXmlType }
     *     
     */
    public void setDefaultAclfAlgorithm(AclfAlgorithmXmlType value) {
        this.defaultAclfAlgorithm = value;
    }

    /**
     * Gets the value of the option property.
     * 
     * @return
     *     possible object is
     *     {@link ContingencyOptionXmlType }
     *     
     */
    public ContingencyOptionXmlType getOption() {
        return option;
    }

    /**
     * Sets the value of the option property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContingencyOptionXmlType }
     *     
     */
    public void setOption(ContingencyOptionXmlType value) {
        this.option = value;
    }

    /**
     * Gets the value of the limitRunCases property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLimitRunCases() {
        return limitRunCases;
    }

    /**
     * Sets the value of the limitRunCases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLimitRunCases(Boolean value) {
        this.limitRunCases = value;
    }

    /**
     * Gets the value of the maxRunCases property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxRunCases() {
        return maxRunCases;
    }

    /**
     * Sets the value of the maxRunCases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxRunCases(Integer value) {
        this.maxRunCases = value;
    }

    /**
     * Gets the value of the aclfAnalysisCase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aclfAnalysisCase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAclfAnalysisCase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AclfAnalysisCaseXmlType }
     * 
     * 
     */
    public List<AclfAnalysisCaseXmlType> getAclfAnalysisCase() {
        if (aclfAnalysisCase == null) {
            aclfAnalysisCase = new ArrayList<AclfAnalysisCaseXmlType>();
        }
        return this.aclfAnalysisCase;
    }

}
