//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.09 at 11:05:44 AM CST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GridAclfOptionXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GridAclfOptionXmlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="returnStudyCase" type="{http://www.interpss.org/Schema/odm/2008}GridReturnStudyCaseEnumType"/>
 *         &lt;element name="calculateViolation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="busVoltagePULimit" type="{http://www.ieee.org/odm/Schema/2008}LimitXmlType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GridAclfOptionXmlType", namespace = "http://www.interpss.org/Schema/odm/2008", propOrder = {
    "returnStudyCase",
    "calculateViolation",
    "busVoltagePULimit"
})
public class GridAclfOptionXmlType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected GridReturnStudyCaseEnumType returnStudyCase;
    protected Boolean calculateViolation;
    protected LimitXmlType busVoltagePULimit;

    /**
     * Gets the value of the returnStudyCase property.
     * 
     * @return
     *     possible object is
     *     {@link GridReturnStudyCaseEnumType }
     *     
     */
    public GridReturnStudyCaseEnumType getReturnStudyCase() {
        return returnStudyCase;
    }

    /**
     * Sets the value of the returnStudyCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link GridReturnStudyCaseEnumType }
     *     
     */
    public void setReturnStudyCase(GridReturnStudyCaseEnumType value) {
        this.returnStudyCase = value;
    }

    /**
     * Gets the value of the calculateViolation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCalculateViolation() {
        return calculateViolation;
    }

    /**
     * Sets the value of the calculateViolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCalculateViolation(Boolean value) {
        this.calculateViolation = value;
    }

    /**
     * Gets the value of the busVoltagePULimit property.
     * 
     * @return
     *     possible object is
     *     {@link LimitXmlType }
     *     
     */
    public LimitXmlType getBusVoltagePULimit() {
        return busVoltagePULimit;
    }

    /**
     * Sets the value of the busVoltagePULimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitXmlType }
     *     
     */
    public void setBusVoltagePULimit(LimitXmlType value) {
        this.busVoltagePULimit = value;
    }

}
