//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.09 at 11:05:44 AM CST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InductionMotorEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InductionMotorEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PSSECIM5"/>
 *     &lt;enumeration value="PSSECIM6"/>
 *     &lt;enumeration value="MOTORW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InductionMotorEnumType")
@XmlEnum
public enum InductionMotorEnumType {

    @XmlEnumValue("PSSECIM5")
    PSSECIM_5("PSSECIM5"),
    @XmlEnumValue("PSSECIM6")
    PSSECIM_6("PSSECIM6"),
    MOTORW("MOTORW");
    private final String value;

    InductionMotorEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InductionMotorEnumType fromValue(String v) {
        for (InductionMotorEnumType c: InductionMotorEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
