//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.15 at 04:30:33 PM MST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LineBranchEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LineBranchEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="OverheadLine"/&gt;
 *     &lt;enumeration value="Breaker"/&gt;
 *     &lt;enumeration value="ZBR"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LineBranchEnumType")
@XmlEnum
public enum LineBranchEnumType {

    @XmlEnumValue("OverheadLine")
    OVERHEAD_LINE("OverheadLine"),
    @XmlEnumValue("Breaker")
    BREAKER("Breaker"),
    ZBR("ZBR"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    LineBranchEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LineBranchEnumType fromValue(String v) {
        for (LineBranchEnumType c: LineBranchEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
