//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 04:40:11 PM CST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LODFMonitorInterfaceXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LODFMonitorInterfaceXmlType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.interpss.org/Schema/odm/2008}LODFMonitorBaseXmlType">
 *       &lt;sequence>
 *         &lt;element name="interface" type="{http://www.ieee.org/odm/Schema/2008}FlowInterfaceRefXmlType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LODFMonitorInterfaceXmlType", namespace = "http://www.interpss.org/Schema/odm/2008", propOrder = {
    "_interface"
})
public class LODFMonitorInterfaceXmlType
    extends LODFMonitorBaseXmlType
{

    @XmlElement(name = "interface", required = true)
    protected FlowInterfaceRefXmlType _interface;

    /**
     * Gets the value of the interface property.
     * 
     * @return
     *     possible object is
     *     {@link FlowInterfaceRefXmlType }
     *     
     */
    public FlowInterfaceRefXmlType getInterface() {
        return _interface;
    }

    /**
     * Sets the value of the interface property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlowInterfaceRefXmlType }
     *     
     */
    public void setInterface(FlowInterfaceRefXmlType value) {
        this._interface = value;
    }

}
