//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.16 at 11:23:00 PM MST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PtCaseDataXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PtCaseDataXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="baseCaseFile" type="{http://www.interpss.org/Schema/odm/2008}PtBaseCaseFileXmlType"/&gt;
 *         &lt;element name="edFile" type="{http://www.interpss.org/Schema/odm/2008}PtEDispatchFileXmlType"/&gt;
 *         &lt;element name="interfaceLimitFilename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PtCaseDataXmlType", namespace = "http://www.interpss.org/Schema/odm/2008", propOrder = {
    "baseCaseFile",
    "edFile",
    "interfaceLimitFilename"
})
public class PtCaseDataXmlType {

    @XmlElement(required = true)
    protected PtBaseCaseFileXmlType baseCaseFile;
    @XmlElement(required = true)
    protected PtEDispatchFileXmlType edFile;
    protected String interfaceLimitFilename;

    /**
     * Gets the value of the baseCaseFile property.
     * 
     * @return
     *     possible object is
     *     {@link PtBaseCaseFileXmlType }
     *     
     */
    public PtBaseCaseFileXmlType getBaseCaseFile() {
        return baseCaseFile;
    }

    /**
     * Sets the value of the baseCaseFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtBaseCaseFileXmlType }
     *     
     */
    public void setBaseCaseFile(PtBaseCaseFileXmlType value) {
        this.baseCaseFile = value;
    }

    /**
     * Gets the value of the edFile property.
     * 
     * @return
     *     possible object is
     *     {@link PtEDispatchFileXmlType }
     *     
     */
    public PtEDispatchFileXmlType getEdFile() {
        return edFile;
    }

    /**
     * Sets the value of the edFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtEDispatchFileXmlType }
     *     
     */
    public void setEdFile(PtEDispatchFileXmlType value) {
        this.edFile = value;
    }

    /**
     * Gets the value of the interfaceLimitFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceLimitFilename() {
        return interfaceLimitFilename;
    }

    /**
     * Sets the value of the interfaceLimitFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceLimitFilename(String value) {
        this.interfaceLimitFilename = value;
    }

}
