//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 04:40:11 PM CST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValueChangeActionEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ValueChangeActionEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="add"/>
 *     &lt;enumeration value="set"/>
 *     &lt;enumeration value="increase"/>
 *     &lt;enumeration value="decrease"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ValueChangeActionEnumType")
@XmlEnum
public enum ValueChangeActionEnumType {

    @XmlEnumValue("add")
    ADD("add"),
    @XmlEnumValue("set")
    SET("set"),
    @XmlEnumValue("increase")
    INCREASE("increase"),
    @XmlEnumValue("decrease")
    DECREASE("decrease");
    private final String value;

    ValueChangeActionEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ValueChangeActionEnumType fromValue(String v) {
        for (ValueChangeActionEnumType c: ValueChangeActionEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
