//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.06 at 07:48:32 PM CST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VSCConverterXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VSCConverterXmlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="busId" type="{http://www.ieee.org/odm/Schema/2008}IDRefRecordXmlType"/>
 *         &lt;element name="dcControlMode" type="{http://www.ieee.org/odm/Schema/2008}VSCDCControlModeEnumType"/>
 *         &lt;element name="acControlMode" type="{http://www.ieee.org/odm/Schema/2008}VSCACControlModeEnumType"/>
 *         &lt;element name="acSetPoint" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="dcSetPoint" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ALoss" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="BLoss" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="MinLoss" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="MVARating" type="{http://www.ieee.org/odm/Schema/2008}ApparentPowerXmlType" minOccurs="0"/>
 *         &lt;element name="ACCurrentRating" type="{http://www.ieee.org/odm/Schema/2008}CurrentXmlType" minOccurs="0"/>
 *         &lt;element name="powerWeightFactor" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="QMax" type="{http://www.ieee.org/odm/Schema/2008}ReactivePowerXmlType" minOccurs="0"/>
 *         &lt;element name="QMin" type="{http://www.ieee.org/odm/Schema/2008}ReactivePowerXmlType" minOccurs="0"/>
 *         &lt;element name="remoteCtrlBusId" type="{http://www.ieee.org/odm/Schema/2008}IDRefRecordXmlType" minOccurs="0"/>
 *         &lt;element name="remoteCtrlPercent" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VSCConverterXmlType", propOrder = {
    "busId",
    "dcControlMode",
    "acControlMode",
    "acSetPoint",
    "dcSetPoint",
    "aLoss",
    "bLoss",
    "minLoss",
    "mvaRating",
    "acCurrentRating",
    "powerWeightFactor",
    "qMax",
    "qMin",
    "remoteCtrlBusId",
    "remoteCtrlPercent"
})
public class VSCConverterXmlType {

    @XmlElement(required = true)
    protected IDRefRecordXmlType busId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected VSCDCControlModeEnumType dcControlMode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected VSCACControlModeEnumType acControlMode;
    protected double acSetPoint;
    protected double dcSetPoint;
    @XmlElement(name = "ALoss")
    protected Double aLoss;
    @XmlElement(name = "BLoss")
    protected Double bLoss;
    @XmlElement(name = "MinLoss")
    protected Double minLoss;
    @XmlElement(name = "MVARating")
    protected ApparentPowerXmlType mvaRating;
    @XmlElement(name = "ACCurrentRating")
    protected CurrentXmlType acCurrentRating;
    protected Double powerWeightFactor;
    @XmlElement(name = "QMax")
    protected ReactivePowerXmlType qMax;
    @XmlElement(name = "QMin")
    protected ReactivePowerXmlType qMin;
    protected IDRefRecordXmlType remoteCtrlBusId;
    protected Double remoteCtrlPercent;

    /**
     * Gets the value of the busId property.
     * 
     * @return
     *     possible object is
     *     {@link IDRefRecordXmlType }
     *     
     */
    public IDRefRecordXmlType getBusId() {
        return busId;
    }

    /**
     * Sets the value of the busId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDRefRecordXmlType }
     *     
     */
    public void setBusId(IDRefRecordXmlType value) {
        this.busId = value;
    }

    /**
     * Gets the value of the dcControlMode property.
     * 
     * @return
     *     possible object is
     *     {@link VSCDCControlModeEnumType }
     *     
     */
    public VSCDCControlModeEnumType getDcControlMode() {
        return dcControlMode;
    }

    /**
     * Sets the value of the dcControlMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link VSCDCControlModeEnumType }
     *     
     */
    public void setDcControlMode(VSCDCControlModeEnumType value) {
        this.dcControlMode = value;
    }

    /**
     * Gets the value of the acControlMode property.
     * 
     * @return
     *     possible object is
     *     {@link VSCACControlModeEnumType }
     *     
     */
    public VSCACControlModeEnumType getAcControlMode() {
        return acControlMode;
    }

    /**
     * Sets the value of the acControlMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link VSCACControlModeEnumType }
     *     
     */
    public void setAcControlMode(VSCACControlModeEnumType value) {
        this.acControlMode = value;
    }

    /**
     * Gets the value of the acSetPoint property.
     * 
     */
    public double getAcSetPoint() {
        return acSetPoint;
    }

    /**
     * Sets the value of the acSetPoint property.
     * 
     */
    public void setAcSetPoint(double value) {
        this.acSetPoint = value;
    }

    /**
     * Gets the value of the dcSetPoint property.
     * 
     */
    public double getDcSetPoint() {
        return dcSetPoint;
    }

    /**
     * Sets the value of the dcSetPoint property.
     * 
     */
    public void setDcSetPoint(double value) {
        this.dcSetPoint = value;
    }

    /**
     * Gets the value of the aLoss property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getALoss() {
        return aLoss;
    }

    /**
     * Sets the value of the aLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setALoss(Double value) {
        this.aLoss = value;
    }

    /**
     * Gets the value of the bLoss property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBLoss() {
        return bLoss;
    }

    /**
     * Sets the value of the bLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBLoss(Double value) {
        this.bLoss = value;
    }

    /**
     * Gets the value of the minLoss property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinLoss() {
        return minLoss;
    }

    /**
     * Sets the value of the minLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinLoss(Double value) {
        this.minLoss = value;
    }

    /**
     * Gets the value of the mvaRating property.
     * 
     * @return
     *     possible object is
     *     {@link ApparentPowerXmlType }
     *     
     */
    public ApparentPowerXmlType getMVARating() {
        return mvaRating;
    }

    /**
     * Sets the value of the mvaRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApparentPowerXmlType }
     *     
     */
    public void setMVARating(ApparentPowerXmlType value) {
        this.mvaRating = value;
    }

    /**
     * Gets the value of the acCurrentRating property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentXmlType }
     *     
     */
    public CurrentXmlType getACCurrentRating() {
        return acCurrentRating;
    }

    /**
     * Sets the value of the acCurrentRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentXmlType }
     *     
     */
    public void setACCurrentRating(CurrentXmlType value) {
        this.acCurrentRating = value;
    }

    /**
     * Gets the value of the powerWeightFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPowerWeightFactor() {
        return powerWeightFactor;
    }

    /**
     * Sets the value of the powerWeightFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPowerWeightFactor(Double value) {
        this.powerWeightFactor = value;
    }

    /**
     * Gets the value of the qMax property.
     * 
     * @return
     *     possible object is
     *     {@link ReactivePowerXmlType }
     *     
     */
    public ReactivePowerXmlType getQMax() {
        return qMax;
    }

    /**
     * Sets the value of the qMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactivePowerXmlType }
     *     
     */
    public void setQMax(ReactivePowerXmlType value) {
        this.qMax = value;
    }

    /**
     * Gets the value of the qMin property.
     * 
     * @return
     *     possible object is
     *     {@link ReactivePowerXmlType }
     *     
     */
    public ReactivePowerXmlType getQMin() {
        return qMin;
    }

    /**
     * Sets the value of the qMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactivePowerXmlType }
     *     
     */
    public void setQMin(ReactivePowerXmlType value) {
        this.qMin = value;
    }

    /**
     * Gets the value of the remoteCtrlBusId property.
     * 
     * @return
     *     possible object is
     *     {@link IDRefRecordXmlType }
     *     
     */
    public IDRefRecordXmlType getRemoteCtrlBusId() {
        return remoteCtrlBusId;
    }

    /**
     * Sets the value of the remoteCtrlBusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDRefRecordXmlType }
     *     
     */
    public void setRemoteCtrlBusId(IDRefRecordXmlType value) {
        this.remoteCtrlBusId = value;
    }

    /**
     * Gets the value of the remoteCtrlPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRemoteCtrlPercent() {
        return remoteCtrlPercent;
    }

    /**
     * Sets the value of the remoteCtrlPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRemoteCtrlPercent(Double value) {
        this.remoteCtrlPercent = value;
    }

}
