//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.26 at 03:05:12 PM CST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AggregateGenBusEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AggregateGenBusEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="STATION_POWER"/&gt;
 *     &lt;enumeration value="ETC_TOR"/&gt;
 *     &lt;enumeration value="DEMAND_RESPONSE"/&gt;
 *     &lt;enumeration value="ParticipateLoad"/&gt;
 *     &lt;enumeration value="DEFAULT_LAP"/&gt;
 *     &lt;enumeration value="SUBLAP"/&gt;
 *     &lt;enumeration value="TH"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AggregateGenBusEnumType", namespace = "http://www.interpss.org/Schema/odm/2008")
@XmlEnum
public enum AggregateGenBusEnumType {

    STATION_POWER("STATION_POWER"),
    ETC_TOR("ETC_TOR"),
    DEMAND_RESPONSE("DEMAND_RESPONSE"),
    @XmlEnumValue("ParticipateLoad")
    PARTICIPATE_LOAD("ParticipateLoad"),
    DEFAULT_LAP("DEFAULT_LAP"),
    SUBLAP("SUBLAP"),
    TH("TH");
    private final String value;

    AggregateGenBusEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AggregateGenBusEnumType fromValue(String v) {
        for (AggregateGenBusEnumType c: AggregateGenBusEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
