//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.28 at 08:34:20 PM MDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BranchOverrideXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BranchOverrideXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}BaseBranchOverrideXmlType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type" type="{http://www.ieee.org/odm/Schema/2008}BranchOverrideEnumType"/&gt;
 *         &lt;element name="ratingBase" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="ratingContingecy" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="monitor" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BranchOverrideXmlType", propOrder = {
    "type",
    "ratingBase",
    "ratingContingecy",
    "monitor"
})
public class BranchOverrideXmlType
    extends BaseBranchOverrideXmlType
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected BranchOverrideEnumType type;
    protected double ratingBase;
    protected double ratingContingecy;
    protected boolean monitor;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BranchOverrideEnumType }
     *     
     */
    public BranchOverrideEnumType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchOverrideEnumType }
     *     
     */
    public void setType(BranchOverrideEnumType value) {
        this.type = value;
    }

    /**
     * Gets the value of the ratingBase property.
     * 
     */
    public double getRatingBase() {
        return ratingBase;
    }

    /**
     * Sets the value of the ratingBase property.
     * 
     */
    public void setRatingBase(double value) {
        this.ratingBase = value;
    }

    /**
     * Gets the value of the ratingContingecy property.
     * 
     */
    public double getRatingContingecy() {
        return ratingContingecy;
    }

    /**
     * Sets the value of the ratingContingecy property.
     * 
     */
    public void setRatingContingecy(double value) {
        this.ratingContingecy = value;
    }

    /**
     * Gets the value of the monitor property.
     * 
     */
    public boolean isMonitor() {
        return monitor;
    }

    /**
     * Sets the value of the monitor property.
     * 
     */
    public void setMonitor(boolean value) {
        this.monitor = value;
    }

}
