//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.01 at 09:47:29 PM PDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConstraintsXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConstraintsXmlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="volLimit" type="{http://www.ieee.org/odm/Schema/2008}VoltageLimitXmlType" minOccurs="0"/>
 *         &lt;element name="activePowerLimit" type="{http://www.ieee.org/odm/Schema/2008}ActivePowerLimitXmlType" minOccurs="0"/>
 *         &lt;element name="reactivePowerLimit" type="{http://www.ieee.org/odm/Schema/2008}ReactivePowerLimitXmlType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConstraintsXmlType", propOrder = {
    "volLimit",
    "activePowerLimit",
    "reactivePowerLimit"
})
public class ConstraintsXmlType {

    protected VoltageLimitXmlType volLimit;
    protected ActivePowerLimitXmlType activePowerLimit;
    protected ReactivePowerLimitXmlType reactivePowerLimit;

    /**
     * Gets the value of the volLimit property.
     * 
     * @return
     *     possible object is
     *     {@link VoltageLimitXmlType }
     *     
     */
    public VoltageLimitXmlType getVolLimit() {
        return volLimit;
    }

    /**
     * Sets the value of the volLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoltageLimitXmlType }
     *     
     */
    public void setVolLimit(VoltageLimitXmlType value) {
        this.volLimit = value;
    }

    /**
     * Gets the value of the activePowerLimit property.
     * 
     * @return
     *     possible object is
     *     {@link ActivePowerLimitXmlType }
     *     
     */
    public ActivePowerLimitXmlType getActivePowerLimit() {
        return activePowerLimit;
    }

    /**
     * Sets the value of the activePowerLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivePowerLimitXmlType }
     *     
     */
    public void setActivePowerLimit(ActivePowerLimitXmlType value) {
        this.activePowerLimit = value;
    }

    /**
     * Gets the value of the reactivePowerLimit property.
     * 
     * @return
     *     possible object is
     *     {@link ReactivePowerLimitXmlType }
     *     
     */
    public ReactivePowerLimitXmlType getReactivePowerLimit() {
        return reactivePowerLimit;
    }

    /**
     * Sets the value of the reactivePowerLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactivePowerLimitXmlType }
     *     
     */
    public void setReactivePowerLimit(ReactivePowerLimitXmlType value) {
        this.reactivePowerLimit = value;
    }

}
