//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.14 at 11:10:38 AM MDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomLfMethodXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomLfMethodXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="firstMethod" type="{http://www.ieee.org/odm/Schema/2008}LfMethodEnumType"/&gt;
 *         &lt;element name="secondMethod" type="{http://www.ieee.org/odm/Schema/2008}LfMethodEnumType"/&gt;
 *         &lt;element name="switchCriteria" type="{http://www.interpss.org/Schema/odm/2008}CustomAclfMethodSwitchCriteriaDataType"/&gt;
 *         &lt;element name="switchIteration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="switchTolerance" type="{http://www.ieee.org/odm/Schema/2008}ApparentPowerXmlType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomLfMethodXmlType", namespace = "http://www.interpss.org/Schema/odm/2008", propOrder = {
    "firstMethod",
    "secondMethod",
    "switchCriteria",
    "switchIteration",
    "switchTolerance"
})
public class CustomLfMethodXmlType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LfMethodEnumType firstMethod;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LfMethodEnumType secondMethod;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CustomAclfMethodSwitchCriteriaDataType switchCriteria;
    protected Integer switchIteration;
    protected ApparentPowerXmlType switchTolerance;

    /**
     * Gets the value of the firstMethod property.
     * 
     * @return
     *     possible object is
     *     {@link LfMethodEnumType }
     *     
     */
    public LfMethodEnumType getFirstMethod() {
        return firstMethod;
    }

    /**
     * Sets the value of the firstMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link LfMethodEnumType }
     *     
     */
    public void setFirstMethod(LfMethodEnumType value) {
        this.firstMethod = value;
    }

    /**
     * Gets the value of the secondMethod property.
     * 
     * @return
     *     possible object is
     *     {@link LfMethodEnumType }
     *     
     */
    public LfMethodEnumType getSecondMethod() {
        return secondMethod;
    }

    /**
     * Sets the value of the secondMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link LfMethodEnumType }
     *     
     */
    public void setSecondMethod(LfMethodEnumType value) {
        this.secondMethod = value;
    }

    /**
     * Gets the value of the switchCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link CustomAclfMethodSwitchCriteriaDataType }
     *     
     */
    public CustomAclfMethodSwitchCriteriaDataType getSwitchCriteria() {
        return switchCriteria;
    }

    /**
     * Sets the value of the switchCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomAclfMethodSwitchCriteriaDataType }
     *     
     */
    public void setSwitchCriteria(CustomAclfMethodSwitchCriteriaDataType value) {
        this.switchCriteria = value;
    }

    /**
     * Gets the value of the switchIteration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSwitchIteration() {
        return switchIteration;
    }

    /**
     * Sets the value of the switchIteration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSwitchIteration(Integer value) {
        this.switchIteration = value;
    }

    /**
     * Gets the value of the switchTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link ApparentPowerXmlType }
     *     
     */
    public ApparentPowerXmlType getSwitchTolerance() {
        return switchTolerance;
    }

    /**
     * Sets the value of the switchTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApparentPowerXmlType }
     *     
     */
    public void setSwitchTolerance(ApparentPowerXmlType value) {
        this.switchTolerance = value;
    }

}
