//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.18 at 03:34:32 PM MDT 
//


package org.ieee.odm.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DclfContingencyXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DclfContingencyXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}IDRecordXmlType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="contingencyBranch" type="{http://www.interpss.org/Schema/odm/2008}DclfContingencyBranchXmlType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DclfContingencyXmlType", namespace = "http://www.interpss.org/Schema/odm/2008", propOrder = {
    "contingencyBranch"
})
public class DclfContingencyXmlType
    extends IDRecordXmlType
{

    protected List<DclfContingencyBranchXmlType> contingencyBranch;

    /**
     * Gets the value of the contingencyBranch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contingencyBranch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContingencyBranch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DclfContingencyBranchXmlType }
     * 
     * 
     */
    public List<DclfContingencyBranchXmlType> getContingencyBranch() {
        if (contingencyBranch == null) {
            contingencyBranch = new ArrayList<DclfContingencyBranchXmlType>();
        }
        return this.contingencyBranch;
    }

}
