//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.14 at 11:10:38 AM MDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DcLineMeteredEndEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DcLineMeteredEndEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="rectifier"/&gt;
 *     &lt;enumeration value="inverter"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DcLineMeteredEndEnumType")
@XmlEnum
public enum DcLineMeteredEndEnumType {

    @XmlEnumValue("rectifier")
    RECTIFIER("rectifier"),
    @XmlEnumValue("inverter")
    INVERTER("inverter");
    private final String value;

    DcLineMeteredEndEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DcLineMeteredEndEnumType fromValue(String v) {
        for (DcLineMeteredEndEnumType c: DcLineMeteredEndEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
