//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.08 at 11:57:40 PM MDT 
//


package org.ieee.odm.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Data structure for defining DC system network   
 * 		
 * 
 * <p>Java class for DcNetworkXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DcNetworkXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}NetworkXmlType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ratedVoltage" type="{http://www.ieee.org/odm/Schema/2008}VoltageXmlType"/&gt;
 *         &lt;element name="pvModelList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.ieee.org/odm/Schema/2008}pvModel" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DcNetworkXmlType", propOrder = {
    "ratedVoltage",
    "pvModelList"
})
public class DcNetworkXmlType
    extends NetworkXmlType
{

    @XmlElement(required = true)
    protected VoltageXmlType ratedVoltage;
    protected DcNetworkXmlType.PvModelList pvModelList;

    /**
     * Gets the value of the ratedVoltage property.
     * 
     * @return
     *     possible object is
     *     {@link VoltageXmlType }
     *     
     */
    public VoltageXmlType getRatedVoltage() {
        return ratedVoltage;
    }

    /**
     * Sets the value of the ratedVoltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoltageXmlType }
     *     
     */
    public void setRatedVoltage(VoltageXmlType value) {
        this.ratedVoltage = value;
    }

    /**
     * Gets the value of the pvModelList property.
     * 
     * @return
     *     possible object is
     *     {@link DcNetworkXmlType.PvModelList }
     *     
     */
    public DcNetworkXmlType.PvModelList getPvModelList() {
        return pvModelList;
    }

    /**
     * Sets the value of the pvModelList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DcNetworkXmlType.PvModelList }
     *     
     */
    public void setPvModelList(DcNetworkXmlType.PvModelList value) {
        this.pvModelList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.ieee.org/odm/Schema/2008}pvModel" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pvModel"
    })
    public static class PvModelList {

        @XmlElementRef(name = "pvModel", namespace = "http://www.ieee.org/odm/Schema/2008", type = JAXBElement.class)
        protected List<JAXBElement<? extends BasePVModelXmlType>> pvModel;

        /**
         * Gets the value of the pvModel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pvModel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPvModel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link PVModelIVCurveXmlType }{@code >}
         * {@link JAXBElement }{@code <}{@link PVModelIVFunctionXmlType }{@code >}
         * {@link JAXBElement }{@code <}{@link BasePVModelXmlType }{@code >}
         * 
         * 
         */
        public List<JAXBElement<? extends BasePVModelXmlType>> getPvModel() {
            if (pvModel == null) {
                pvModel = new ArrayList<JAXBElement<? extends BasePVModelXmlType>>();
            }
            return this.pvModel;
        }

    }

}
