//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.28 at 08:34:20 PM MDT 
//


package org.ieee.odm.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 		
 * 
 * <p>Java class for DistributionNetXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistributionNetXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}NetworkXmlType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="positiveSeqDataOnly" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="scStd" type="{http://www.ieee.org/odm/Schema/2008}ScAnalysisStdEnumType"/&gt;
 *         &lt;element name="scPoint" type="{http://www.ieee.org/odm/Schema/2008}DistScPointXmlType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributionNetXmlType", propOrder = {
    "positiveSeqDataOnly",
    "scStd",
    "scPoint"
})
public class DistributionNetXmlType
    extends NetworkXmlType
{

    protected boolean positiveSeqDataOnly;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ScAnalysisStdEnumType scStd;
    protected List<DistScPointXmlType> scPoint;

    /**
     * Gets the value of the positiveSeqDataOnly property.
     * 
     */
    public boolean isPositiveSeqDataOnly() {
        return positiveSeqDataOnly;
    }

    /**
     * Sets the value of the positiveSeqDataOnly property.
     * 
     */
    public void setPositiveSeqDataOnly(boolean value) {
        this.positiveSeqDataOnly = value;
    }

    /**
     * Gets the value of the scStd property.
     * 
     * @return
     *     possible object is
     *     {@link ScAnalysisStdEnumType }
     *     
     */
    public ScAnalysisStdEnumType getScStd() {
        return scStd;
    }

    /**
     * Sets the value of the scStd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScAnalysisStdEnumType }
     *     
     */
    public void setScStd(ScAnalysisStdEnumType value) {
        this.scStd = value;
    }

    /**
     * Gets the value of the scPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DistScPointXmlType }
     * 
     * 
     */
    public List<DistScPointXmlType> getScPoint() {
        if (scPoint == null) {
            scPoint = new ArrayList<DistScPointXmlType>();
        }
        return this.scPoint;
    }

}
