//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.14 at 11:10:38 AM MDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 		Under/over voltage generator trip relay
 * 		
 * 
 * <p>Java class for GenRelayVTGTPATXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenRelayVTGTPATXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}GenRelayXmlType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VL" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="VU" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Tp" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Tb" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenRelayVTGTPATXmlType", propOrder = {
    "vl",
    "vu",
    "tp",
    "tb"
})
public class GenRelayVTGTPATXmlType
    extends GenRelayXmlType
{

    @XmlElement(name = "VL", defaultValue = "0.0")
    protected Double vl;
    @XmlElement(name = "VU", defaultValue = "0.0")
    protected Double vu;
    @XmlElement(name = "Tp", defaultValue = "0.0")
    protected Double tp;
    @XmlElement(name = "Tb", defaultValue = "0.0")
    protected Double tb;

    /**
     * Gets the value of the vl property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVL() {
        return vl;
    }

    /**
     * Sets the value of the vl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVL(Double value) {
        this.vl = value;
    }

    /**
     * Gets the value of the vu property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVU() {
        return vu;
    }

    /**
     * Sets the value of the vu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVU(Double value) {
        this.vu = value;
    }

    /**
     * Gets the value of the tp property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTp() {
        return tp;
    }

    /**
     * Sets the value of the tp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTp(Double value) {
        this.tp = value;
    }

    /**
     * Gets the value of the tb property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTb() {
        return tb;
    }

    /**
     * Sets the value of the tb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTb(Double value) {
        this.tb = value;
    }

}
