//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.18 at 03:34:32 PM MDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GovBPAHydroTurbineGHXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GovBPAHydroTurbineGHXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}GovernorModelXmlType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PMAX" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="R" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="TG" type="{http://www.ieee.org/odm/Schema/2008}TimePeriodXmlType"/&gt;
 *         &lt;element name="TP" type="{http://www.ieee.org/odm/Schema/2008}TimePeriodXmlType"/&gt;
 *         &lt;element name="Td" type="{http://www.ieee.org/odm/Schema/2008}TimePeriodXmlType"/&gt;
 *         &lt;element name="TwHalf" type="{http://www.ieee.org/odm/Schema/2008}TimePeriodXmlType"/&gt;
 *         &lt;element name="VOpen" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="VClose" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Dd" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Epsilon" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GovBPAHydroTurbineGHXmlType", propOrder = {
    "pmax",
    "r",
    "tg",
    "tp",
    "td",
    "twHalf",
    "vOpen",
    "vClose",
    "dd",
    "epsilon"
})
public class GovBPAHydroTurbineGHXmlType
    extends GovernorModelXmlType
{

    @XmlElement(name = "PMAX")
    protected double pmax;
    @XmlElement(name = "R")
    protected double r;
    @XmlElement(name = "TG", required = true)
    protected TimePeriodXmlType tg;
    @XmlElement(name = "TP", required = true)
    protected TimePeriodXmlType tp;
    @XmlElement(name = "Td", required = true)
    protected TimePeriodXmlType td;
    @XmlElement(name = "TwHalf", required = true)
    protected TimePeriodXmlType twHalf;
    @XmlElement(name = "VOpen")
    protected double vOpen;
    @XmlElement(name = "VClose")
    protected double vClose;
    @XmlElement(name = "Dd")
    protected double dd;
    @XmlElement(name = "Epsilon")
    protected double epsilon;

    /**
     * Gets the value of the pmax property.
     * 
     */
    public double getPMAX() {
        return pmax;
    }

    /**
     * Sets the value of the pmax property.
     * 
     */
    public void setPMAX(double value) {
        this.pmax = value;
    }

    /**
     * Gets the value of the r property.
     * 
     */
    public double getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     * 
     */
    public void setR(double value) {
        this.r = value;
    }

    /**
     * Gets the value of the tg property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public TimePeriodXmlType getTG() {
        return tg;
    }

    /**
     * Sets the value of the tg property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public void setTG(TimePeriodXmlType value) {
        this.tg = value;
    }

    /**
     * Gets the value of the tp property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public TimePeriodXmlType getTP() {
        return tp;
    }

    /**
     * Sets the value of the tp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public void setTP(TimePeriodXmlType value) {
        this.tp = value;
    }

    /**
     * Gets the value of the td property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public TimePeriodXmlType getTd() {
        return td;
    }

    /**
     * Sets the value of the td property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public void setTd(TimePeriodXmlType value) {
        this.td = value;
    }

    /**
     * Gets the value of the twHalf property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public TimePeriodXmlType getTwHalf() {
        return twHalf;
    }

    /**
     * Sets the value of the twHalf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public void setTwHalf(TimePeriodXmlType value) {
        this.twHalf = value;
    }

    /**
     * Gets the value of the vOpen property.
     * 
     */
    public double getVOpen() {
        return vOpen;
    }

    /**
     * Sets the value of the vOpen property.
     * 
     */
    public void setVOpen(double value) {
        this.vOpen = value;
    }

    /**
     * Gets the value of the vClose property.
     * 
     */
    public double getVClose() {
        return vClose;
    }

    /**
     * Sets the value of the vClose property.
     * 
     */
    public void setVClose(double value) {
        this.vClose = value;
    }

    /**
     * Gets the value of the dd property.
     * 
     */
    public double getDd() {
        return dd;
    }

    /**
     * Sets the value of the dd property.
     * 
     */
    public void setDd(double value) {
        this.dd = value;
    }

    /**
     * Gets the value of the epsilon property.
     * 
     */
    public double getEpsilon() {
        return epsilon;
    }

    /**
     * Sets the value of the epsilon property.
     * 
     */
    public void setEpsilon(double value) {
        this.epsilon = value;
    }

}
