//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.14 at 06:23:19 PM MDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GovSteamTCSRXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GovSteamTCSRXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}GovSteamNRXmlType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TRH" type="{http://www.ieee.org/odm/Schema/2008}TimePeriodXmlType"/&gt;
 *         &lt;element name="TCO" type="{http://www.ieee.org/odm/Schema/2008}TimePeriodXmlType"/&gt;
 *         &lt;element name="FHP" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="FIP" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="FLP" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GovSteamTCSRXmlType", propOrder = {
    "trh",
    "tco",
    "fhp",
    "fip",
    "flp"
})
public class GovSteamTCSRXmlType
    extends GovSteamNRXmlType
{

    @XmlElement(name = "TRH", required = true)
    protected TimePeriodXmlType trh;
    @XmlElement(name = "TCO", required = true)
    protected TimePeriodXmlType tco;
    @XmlElement(name = "FHP")
    protected double fhp;
    @XmlElement(name = "FIP")
    protected double fip;
    @XmlElement(name = "FLP")
    protected double flp;

    /**
     * Gets the value of the trh property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public TimePeriodXmlType getTRH() {
        return trh;
    }

    /**
     * Sets the value of the trh property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public void setTRH(TimePeriodXmlType value) {
        this.trh = value;
    }

    /**
     * Gets the value of the tco property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public TimePeriodXmlType getTCO() {
        return tco;
    }

    /**
     * Sets the value of the tco property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodXmlType }
     *     
     */
    public void setTCO(TimePeriodXmlType value) {
        this.tco = value;
    }

    /**
     * Gets the value of the fhp property.
     * 
     */
    public double getFHP() {
        return fhp;
    }

    /**
     * Sets the value of the fhp property.
     * 
     */
    public void setFHP(double value) {
        this.fhp = value;
    }

    /**
     * Gets the value of the fip property.
     * 
     */
    public double getFIP() {
        return fip;
    }

    /**
     * Sets the value of the fip property.
     * 
     */
    public void setFIP(double value) {
        this.fip = value;
    }

    /**
     * Gets the value of the flp property.
     * 
     */
    public double getFLP() {
        return flp;
    }

    /**
     * Sets the value of the flp property.
     * 
     */
    public void setFLP(double value) {
        this.flp = value;
    }

}
