//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.08 at 02:42:31 PM MDT 
//


package org.ieee.odm.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PSXfrDStabXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PSXfrDStabXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}PSXfrShortCircuitXmlType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="xfrRelay" type="{http://www.ieee.org/odm/Schema/2008}XfrRelayXmlType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PSXfrDStabXmlType", propOrder = {
    "xfrRelay"
})
public class PSXfrDStabXmlType
    extends PSXfrShortCircuitXmlType
{

    protected List<XfrRelayXmlType> xfrRelay;

    /**
     * Gets the value of the xfrRelay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xfrRelay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXfrRelay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XfrRelayXmlType }
     * 
     * 
     */
    public List<XfrRelayXmlType> getXfrRelay() {
        if (xfrRelay == null) {
            xfrRelay = new ArrayList<XfrRelayXmlType>();
        }
        return this.xfrRelay;
    }

}
