//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.14 at 11:10:38 AM MDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			I/V function based PV model
 * 		
 * 
 * <p>Java class for PVModelIVFunctionXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PVModelIVFunctionXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}BasePVModelXmlType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="a" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="b" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="c" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="d" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="e" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="f" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="sign" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="shadingFactor" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PVModelIVFunctionXmlType", propOrder = {
    "a",
    "b",
    "c",
    "d",
    "e",
    "f"
})
public class PVModelIVFunctionXmlType
    extends BasePVModelXmlType
{

    protected double a;
    protected double b;
    protected double c;
    protected double d;
    protected double e;
    protected double f;
    @XmlAttribute(name = "sign", required = true)
    protected int sign;
    @XmlAttribute(name = "shadingFactor", required = true)
    protected double shadingFactor;

    /**
     * Gets the value of the a property.
     * 
     */
    public double getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     */
    public void setA(double value) {
        this.a = value;
    }

    /**
     * Gets the value of the b property.
     * 
     */
    public double getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     */
    public void setB(double value) {
        this.b = value;
    }

    /**
     * Gets the value of the c property.
     * 
     */
    public double getC() {
        return c;
    }

    /**
     * Sets the value of the c property.
     * 
     */
    public void setC(double value) {
        this.c = value;
    }

    /**
     * Gets the value of the d property.
     * 
     */
    public double getD() {
        return d;
    }

    /**
     * Sets the value of the d property.
     * 
     */
    public void setD(double value) {
        this.d = value;
    }

    /**
     * Gets the value of the e property.
     * 
     */
    public double getE() {
        return e;
    }

    /**
     * Sets the value of the e property.
     * 
     */
    public void setE(double value) {
        this.e = value;
    }

    /**
     * Gets the value of the f property.
     * 
     */
    public double getF() {
        return f;
    }

    /**
     * Sets the value of the f property.
     * 
     */
    public void setF(double value) {
        this.f = value;
    }

    /**
     * Gets the value of the sign property.
     * 
     */
    public int getSign() {
        return sign;
    }

    /**
     * Sets the value of the sign property.
     * 
     */
    public void setSign(int value) {
        this.sign = value;
    }

    /**
     * Gets the value of the shadingFactor property.
     * 
     */
    public double getShadingFactor() {
        return shadingFactor;
    }

    /**
     * Sets the value of the shadingFactor property.
     * 
     */
    public void setShadingFactor(double value) {
        this.shadingFactor = value;
    }

}
