//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.14 at 11:10:38 AM MDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScheduledBranchOutageXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScheduledBranchOutageXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ieee.org/odm/Schema/2008}BranchRefXmlType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dueOutDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dueBackDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="resourceType" type="{http://www.interpss.org/Schema/odm/2008}ScheduledOutageResourceEnumType"/&gt;
 *         &lt;element name="branchType" type="{http://www.interpss.org/Schema/odm/2008}ScheduledOutageBranchEnumType"/&gt;
 *         &lt;element name="voltage" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="fromBusNo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="toBusNo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="fromBusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fromBusVoltage" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="toBusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="toBusVoltage" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="offLine" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScheduledBranchOutageXmlType", namespace = "http://www.interpss.org/Schema/odm/2008", propOrder = {
    "dueOutDate",
    "dueBackDate",
    "resourceType",
    "branchType",
    "voltage",
    "fromBusNo",
    "toBusNo",
    "fromBusName",
    "fromBusVoltage",
    "toBusName",
    "toBusVoltage"
})
public class ScheduledBranchOutageXmlType
    extends BranchRefXmlType
{

    @XmlElement(required = true)
    protected String dueOutDate;
    @XmlElement(required = true)
    protected String dueBackDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ScheduledOutageResourceEnumType resourceType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ScheduledOutageBranchEnumType branchType;
    protected Double voltage;
    protected int fromBusNo;
    protected int toBusNo;
    protected String fromBusName;
    protected Double fromBusVoltage;
    protected String toBusName;
    protected Double toBusVoltage;
    @XmlAttribute(name = "offLine")
    protected Boolean offLine;

    /**
     * Gets the value of the dueOutDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueOutDate() {
        return dueOutDate;
    }

    /**
     * Sets the value of the dueOutDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueOutDate(String value) {
        this.dueOutDate = value;
    }

    /**
     * Gets the value of the dueBackDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueBackDate() {
        return dueBackDate;
    }

    /**
     * Sets the value of the dueBackDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueBackDate(String value) {
        this.dueBackDate = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduledOutageResourceEnumType }
     *     
     */
    public ScheduledOutageResourceEnumType getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduledOutageResourceEnumType }
     *     
     */
    public void setResourceType(ScheduledOutageResourceEnumType value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the branchType property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduledOutageBranchEnumType }
     *     
     */
    public ScheduledOutageBranchEnumType getBranchType() {
        return branchType;
    }

    /**
     * Sets the value of the branchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduledOutageBranchEnumType }
     *     
     */
    public void setBranchType(ScheduledOutageBranchEnumType value) {
        this.branchType = value;
    }

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVoltage(Double value) {
        this.voltage = value;
    }

    /**
     * Gets the value of the fromBusNo property.
     * 
     */
    public int getFromBusNo() {
        return fromBusNo;
    }

    /**
     * Sets the value of the fromBusNo property.
     * 
     */
    public void setFromBusNo(int value) {
        this.fromBusNo = value;
    }

    /**
     * Gets the value of the toBusNo property.
     * 
     */
    public int getToBusNo() {
        return toBusNo;
    }

    /**
     * Sets the value of the toBusNo property.
     * 
     */
    public void setToBusNo(int value) {
        this.toBusNo = value;
    }

    /**
     * Gets the value of the fromBusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromBusName() {
        return fromBusName;
    }

    /**
     * Sets the value of the fromBusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromBusName(String value) {
        this.fromBusName = value;
    }

    /**
     * Gets the value of the fromBusVoltage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFromBusVoltage() {
        return fromBusVoltage;
    }

    /**
     * Sets the value of the fromBusVoltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFromBusVoltage(Double value) {
        this.fromBusVoltage = value;
    }

    /**
     * Gets the value of the toBusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToBusName() {
        return toBusName;
    }

    /**
     * Sets the value of the toBusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToBusName(String value) {
        this.toBusName = value;
    }

    /**
     * Gets the value of the toBusVoltage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getToBusVoltage() {
        return toBusVoltage;
    }

    /**
     * Sets the value of the toBusVoltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setToBusVoltage(Double value) {
        this.toBusVoltage = value;
    }

    /**
     * Gets the value of the offLine property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOffLine() {
        return offLine;
    }

    /**
     * Sets the value of the offLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOffLine(Boolean value) {
        this.offLine = value;
    }

}
