//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.01 at 04:02:51 PM MDT 
//


package org.ieee.odm.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SwitchedShuntXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SwitchedShuntXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="desiredVoltageRange" type="{http://www.ieee.org/odm/Schema/2008}VoltageLimitXmlType"/&gt;
 *         &lt;element name="bInit" type="{http://www.ieee.org/odm/Schema/2008}ReactivePowerXmlType"/&gt;
 *         &lt;element name="VarPercent" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="block" type="{http://www.ieee.org/odm/Schema/2008}SwitchedShuntBlockXmlType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="remoteControlledBus" type="{http://www.ieee.org/odm/Schema/2008}IDRefRecordXmlType" minOccurs="0"/&gt;
 *         &lt;element name="vscDcLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bZeroSeqPerSection" type="{http://www.ieee.org/odm/Schema/2008}YUnitType" minOccurs="0"/&gt;
 *         &lt;element name="bPosSeqPerSection" type="{http://www.ieee.org/odm/Schema/2008}YUnitType" minOccurs="0"/&gt;
 *         &lt;element name="gZeroSeqPerSection" type="{http://www.ieee.org/odm/Schema/2008}YUnitType" minOccurs="0"/&gt;
 *         &lt;element name="gPosSeqPerSection" type="{http://www.ieee.org/odm/Schema/2008}YUnitType" minOccurs="0"/&gt;
 *         &lt;element name="maxSections" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="maxVoltage" type="{http://www.ieee.org/odm/Schema/2008}VoltageXmlType" minOccurs="0"/&gt;
 *         &lt;element name="minVoltage" type="{http://www.ieee.org/odm/Schema/2008}VoltageXmlType" minOccurs="0"/&gt;
 *         &lt;element name="norminalQOutput" type="{http://www.ieee.org/odm/Schema/2008}ReactivePowerXmlType" minOccurs="0"/&gt;
 *         &lt;element name="norminalVoltage" type="{http://www.ieee.org/odm/Schema/2008}VoltageXmlType" minOccurs="0"/&gt;
 *         &lt;element name="norminalSwitchedInSections" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="slop" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="reactivePowerPerSec" type="{http://www.ieee.org/odm/Schema/2008}ReactivePowerXmlType" minOccurs="0"/&gt;
 *         &lt;element name="desiredReactivePowerRange" type="{http://www.ieee.org/odm/Schema/2008}ReactivePowerLimitXmlType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="mode" use="required" type="{http://www.ieee.org/odm/Schema/2008}SwitchedShuntModeEnumType" /&gt;
 *       &lt;attribute name="adjMethod" use="required" type="{http://www.ieee.org/odm/Schema/2008}SwitchedShuntAdjustMethodEnumType" /&gt;
 *       &lt;attribute name="offLine" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SwitchedShuntXmlType", propOrder = {
    "desiredVoltageRange",
    "bInit",
    "varPercent",
    "block",
    "remoteControlledBus",
    "vscDcLine",
    "bZeroSeqPerSection",
    "bPosSeqPerSection",
    "gZeroSeqPerSection",
    "gPosSeqPerSection",
    "maxSections",
    "maxVoltage",
    "minVoltage",
    "norminalQOutput",
    "norminalVoltage",
    "norminalSwitchedInSections",
    "slop",
    "reactivePowerPerSec",
    "desiredReactivePowerRange"
})
public class SwitchedShuntXmlType {

    @XmlElement(required = true)
    protected VoltageLimitXmlType desiredVoltageRange;
    @XmlElement(required = true)
    protected ReactivePowerXmlType bInit;
    @XmlElement(name = "VarPercent")
    protected Double varPercent;
    @XmlElement(required = true)
    protected List<SwitchedShuntBlockXmlType> block;
    protected IDRefRecordXmlType remoteControlledBus;
    protected String vscDcLine;
    @XmlSchemaType(name = "string")
    protected YUnitType bZeroSeqPerSection;
    @XmlSchemaType(name = "string")
    protected YUnitType bPosSeqPerSection;
    @XmlSchemaType(name = "string")
    protected YUnitType gZeroSeqPerSection;
    @XmlSchemaType(name = "string")
    protected YUnitType gPosSeqPerSection;
    protected Long maxSections;
    protected VoltageXmlType maxVoltage;
    protected VoltageXmlType minVoltage;
    protected ReactivePowerXmlType norminalQOutput;
    protected VoltageXmlType norminalVoltage;
    protected Long norminalSwitchedInSections;
    protected Double slop;
    protected ReactivePowerXmlType reactivePowerPerSec;
    protected ReactivePowerLimitXmlType desiredReactivePowerRange;
    @XmlAttribute(name = "mode", required = true)
    protected SwitchedShuntModeEnumType mode;
    @XmlAttribute(name = "adjMethod", required = true)
    protected SwitchedShuntAdjustMethodEnumType adjMethod;
    @XmlAttribute(name = "offLine", required = true)
    protected boolean offLine;

    /**
     * Gets the value of the desiredVoltageRange property.
     * 
     * @return
     *     possible object is
     *     {@link VoltageLimitXmlType }
     *     
     */
    public VoltageLimitXmlType getDesiredVoltageRange() {
        return desiredVoltageRange;
    }

    /**
     * Sets the value of the desiredVoltageRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoltageLimitXmlType }
     *     
     */
    public void setDesiredVoltageRange(VoltageLimitXmlType value) {
        this.desiredVoltageRange = value;
    }

    /**
     * Gets the value of the bInit property.
     * 
     * @return
     *     possible object is
     *     {@link ReactivePowerXmlType }
     *     
     */
    public ReactivePowerXmlType getBInit() {
        return bInit;
    }

    /**
     * Sets the value of the bInit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactivePowerXmlType }
     *     
     */
    public void setBInit(ReactivePowerXmlType value) {
        this.bInit = value;
    }

    /**
     * Gets the value of the varPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVarPercent() {
        return varPercent;
    }

    /**
     * Sets the value of the varPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVarPercent(Double value) {
        this.varPercent = value;
    }

    /**
     * Gets the value of the block property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the block property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SwitchedShuntBlockXmlType }
     * 
     * 
     */
    public List<SwitchedShuntBlockXmlType> getBlock() {
        if (block == null) {
            block = new ArrayList<SwitchedShuntBlockXmlType>();
        }
        return this.block;
    }

    /**
     * Gets the value of the remoteControlledBus property.
     * 
     * @return
     *     possible object is
     *     {@link IDRefRecordXmlType }
     *     
     */
    public IDRefRecordXmlType getRemoteControlledBus() {
        return remoteControlledBus;
    }

    /**
     * Sets the value of the remoteControlledBus property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDRefRecordXmlType }
     *     
     */
    public void setRemoteControlledBus(IDRefRecordXmlType value) {
        this.remoteControlledBus = value;
    }

    /**
     * Gets the value of the vscDcLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVscDcLine() {
        return vscDcLine;
    }

    /**
     * Sets the value of the vscDcLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVscDcLine(String value) {
        this.vscDcLine = value;
    }

    /**
     * Gets the value of the bZeroSeqPerSection property.
     * 
     * @return
     *     possible object is
     *     {@link YUnitType }
     *     
     */
    public YUnitType getBZeroSeqPerSection() {
        return bZeroSeqPerSection;
    }

    /**
     * Sets the value of the bZeroSeqPerSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link YUnitType }
     *     
     */
    public void setBZeroSeqPerSection(YUnitType value) {
        this.bZeroSeqPerSection = value;
    }

    /**
     * Gets the value of the bPosSeqPerSection property.
     * 
     * @return
     *     possible object is
     *     {@link YUnitType }
     *     
     */
    public YUnitType getBPosSeqPerSection() {
        return bPosSeqPerSection;
    }

    /**
     * Sets the value of the bPosSeqPerSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link YUnitType }
     *     
     */
    public void setBPosSeqPerSection(YUnitType value) {
        this.bPosSeqPerSection = value;
    }

    /**
     * Gets the value of the gZeroSeqPerSection property.
     * 
     * @return
     *     possible object is
     *     {@link YUnitType }
     *     
     */
    public YUnitType getGZeroSeqPerSection() {
        return gZeroSeqPerSection;
    }

    /**
     * Sets the value of the gZeroSeqPerSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link YUnitType }
     *     
     */
    public void setGZeroSeqPerSection(YUnitType value) {
        this.gZeroSeqPerSection = value;
    }

    /**
     * Gets the value of the gPosSeqPerSection property.
     * 
     * @return
     *     possible object is
     *     {@link YUnitType }
     *     
     */
    public YUnitType getGPosSeqPerSection() {
        return gPosSeqPerSection;
    }

    /**
     * Sets the value of the gPosSeqPerSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link YUnitType }
     *     
     */
    public void setGPosSeqPerSection(YUnitType value) {
        this.gPosSeqPerSection = value;
    }

    /**
     * Gets the value of the maxSections property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxSections() {
        return maxSections;
    }

    /**
     * Sets the value of the maxSections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxSections(Long value) {
        this.maxSections = value;
    }

    /**
     * Gets the value of the maxVoltage property.
     * 
     * @return
     *     possible object is
     *     {@link VoltageXmlType }
     *     
     */
    public VoltageXmlType getMaxVoltage() {
        return maxVoltage;
    }

    /**
     * Sets the value of the maxVoltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoltageXmlType }
     *     
     */
    public void setMaxVoltage(VoltageXmlType value) {
        this.maxVoltage = value;
    }

    /**
     * Gets the value of the minVoltage property.
     * 
     * @return
     *     possible object is
     *     {@link VoltageXmlType }
     *     
     */
    public VoltageXmlType getMinVoltage() {
        return minVoltage;
    }

    /**
     * Sets the value of the minVoltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoltageXmlType }
     *     
     */
    public void setMinVoltage(VoltageXmlType value) {
        this.minVoltage = value;
    }

    /**
     * Gets the value of the norminalQOutput property.
     * 
     * @return
     *     possible object is
     *     {@link ReactivePowerXmlType }
     *     
     */
    public ReactivePowerXmlType getNorminalQOutput() {
        return norminalQOutput;
    }

    /**
     * Sets the value of the norminalQOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactivePowerXmlType }
     *     
     */
    public void setNorminalQOutput(ReactivePowerXmlType value) {
        this.norminalQOutput = value;
    }

    /**
     * Gets the value of the norminalVoltage property.
     * 
     * @return
     *     possible object is
     *     {@link VoltageXmlType }
     *     
     */
    public VoltageXmlType getNorminalVoltage() {
        return norminalVoltage;
    }

    /**
     * Sets the value of the norminalVoltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoltageXmlType }
     *     
     */
    public void setNorminalVoltage(VoltageXmlType value) {
        this.norminalVoltage = value;
    }

    /**
     * Gets the value of the norminalSwitchedInSections property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNorminalSwitchedInSections() {
        return norminalSwitchedInSections;
    }

    /**
     * Sets the value of the norminalSwitchedInSections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNorminalSwitchedInSections(Long value) {
        this.norminalSwitchedInSections = value;
    }

    /**
     * Gets the value of the slop property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSlop() {
        return slop;
    }

    /**
     * Sets the value of the slop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSlop(Double value) {
        this.slop = value;
    }

    /**
     * Gets the value of the reactivePowerPerSec property.
     * 
     * @return
     *     possible object is
     *     {@link ReactivePowerXmlType }
     *     
     */
    public ReactivePowerXmlType getReactivePowerPerSec() {
        return reactivePowerPerSec;
    }

    /**
     * Sets the value of the reactivePowerPerSec property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactivePowerXmlType }
     *     
     */
    public void setReactivePowerPerSec(ReactivePowerXmlType value) {
        this.reactivePowerPerSec = value;
    }

    /**
     * Gets the value of the desiredReactivePowerRange property.
     * 
     * @return
     *     possible object is
     *     {@link ReactivePowerLimitXmlType }
     *     
     */
    public ReactivePowerLimitXmlType getDesiredReactivePowerRange() {
        return desiredReactivePowerRange;
    }

    /**
     * Sets the value of the desiredReactivePowerRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactivePowerLimitXmlType }
     *     
     */
    public void setDesiredReactivePowerRange(ReactivePowerLimitXmlType value) {
        this.desiredReactivePowerRange = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchedShuntModeEnumType }
     *     
     */
    public SwitchedShuntModeEnumType getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchedShuntModeEnumType }
     *     
     */
    public void setMode(SwitchedShuntModeEnumType value) {
        this.mode = value;
    }

    /**
     * Gets the value of the adjMethod property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchedShuntAdjustMethodEnumType }
     *     
     */
    public SwitchedShuntAdjustMethodEnumType getAdjMethod() {
        return adjMethod;
    }

    /**
     * Sets the value of the adjMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchedShuntAdjustMethodEnumType }
     *     
     */
    public void setAdjMethod(SwitchedShuntAdjustMethodEnumType value) {
        this.adjMethod = value;
    }

    /**
     * Gets the value of the offLine property.
     * 
     */
    public boolean isOffLine() {
        return offLine;
    }

    /**
     * Sets the value of the offLine property.
     * 
     */
    public void setOffLine(boolean value) {
        this.offLine = value;
    }

}
