//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.18 at 03:34:32 PM MDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TapAdjustBusLocationEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TapAdjustBusLocationEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="TerminalBus"/&gt;
 *     &lt;enumeration value="NearFromBus"/&gt;
 *     &lt;enumeration value="NearToBus"/&gt;
 *     &lt;enumeration value="FromBus"/&gt;
 *     &lt;enumeration value="ToBus"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TapAdjustBusLocationEnumType")
@XmlEnum
public enum TapAdjustBusLocationEnumType {

    @XmlEnumValue("TerminalBus")
    TERMINAL_BUS("TerminalBus"),
    @XmlEnumValue("NearFromBus")
    NEAR_FROM_BUS("NearFromBus"),
    @XmlEnumValue("NearToBus")
    NEAR_TO_BUS("NearToBus"),
    @XmlEnumValue("FromBus")
    FROM_BUS("FromBus"),
    @XmlEnumValue("ToBus")
    TO_BUS("ToBus");
    private final String value;

    TapAdjustBusLocationEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TapAdjustBusLocationEnumType fromValue(String v) {
        for (TapAdjustBusLocationEnumType c: TapAdjustBusLocationEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
