//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.14 at 11:10:38 AM MDT 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XformerConnectionXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XformerConnectionXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="grounding" type="{http://www.ieee.org/odm/Schema/2008}GroundingXmlType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="xfrConnection" use="required" type="{http://www.ieee.org/odm/Schema/2008}XformrtConnectionEnumType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XformerConnectionXmlType", propOrder = {
    "grounding"
})
public class XformerConnectionXmlType {

    protected GroundingXmlType grounding;
    @XmlAttribute(name = "xfrConnection", required = true)
    protected XformrtConnectionEnumType xfrConnection;

    /**
     * Gets the value of the grounding property.
     * 
     * @return
     *     possible object is
     *     {@link GroundingXmlType }
     *     
     */
    public GroundingXmlType getGrounding() {
        return grounding;
    }

    /**
     * Sets the value of the grounding property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroundingXmlType }
     *     
     */
    public void setGrounding(GroundingXmlType value) {
        this.grounding = value;
    }

    /**
     * Gets the value of the xfrConnection property.
     * 
     * @return
     *     possible object is
     *     {@link XformrtConnectionEnumType }
     *     
     */
    public XformrtConnectionEnumType getXfrConnection() {
        return xfrConnection;
    }

    /**
     * Sets the value of the xfrConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link XformrtConnectionEnumType }
     *     
     */
    public void setXfrConnection(XformrtConnectionEnumType value) {
        this.xfrConnection = value;
    }

}
