//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.13 at 08:40:51 AM CST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for AclfLoadCodeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AclfLoadCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CONST_P"/>
 *     &lt;enumeration value="CONST_I"/>
 *     &lt;enumeration value="CONST_Z"/>
 *     &lt;enumeration value="EXPONENTIAL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum AclfLoadCodeEnumType {

    CONST_P,
    CONST_I,
    CONST_Z,
    EXPONENTIAL;

    public String value() {
        return name();
    }

    public static AclfLoadCodeEnumType fromValue(String v) {
        return valueOf(v);
    }

}
