//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.13 at 08:40:51 AM CST 
//


package org.ieee.odm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Data structure for hourly ED info based PowerTrading analysis
 * 		
 * 
 * <p>Java class for PTradingEDHourlyAnalysisXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PTradingEDHourlyAnalysisXmlType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.interpss.org/Schema/odm/2008}PTradingAnalysisXmlType">
 *       &lt;sequence>
 *         &lt;element name="caseData" type="{http://www.interpss.org/Schema/odm/2008}PtCaseDataXmlType"/>
 *         &lt;element name="aclfAnalysis" type="{http://www.interpss.org/Schema/odm/2008}PtAclfAnalysisXmlType" minOccurs="0"/>
 *         &lt;element name="branchAnalysis" type="{http://www.interpss.org/Schema/odm/2008}PtBranchAnalysisXmlType" minOccurs="0"/>
 *         &lt;element name="genLossFactorAnalysis" type="{http://www.interpss.org/Schema/odm/2008}PtGenLossFactorXmlType" minOccurs="0"/>
 *         &lt;element name="outputOption" type="{http://www.interpss.org/Schema/odm/2008}PtAnalysisOutputXmlType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PTradingEDHourlyAnalysisXmlType", namespace = "http://www.interpss.org/Schema/odm/2008", propOrder = {
    "caseData",
    "aclfAnalysis",
    "branchAnalysis",
    "genLossFactorAnalysis",
    "outputOption"
})
public class PTradingEDHourlyAnalysisXmlType
    extends PTradingAnalysisXmlType
{

    @XmlElement(namespace = "http://www.interpss.org/Schema/odm/2008", required = true)
    protected PtCaseDataXmlType caseData;
    @XmlElement(namespace = "http://www.interpss.org/Schema/odm/2008")
    protected PtAclfAnalysisXmlType aclfAnalysis;
    @XmlElement(namespace = "http://www.interpss.org/Schema/odm/2008")
    protected PtBranchAnalysisXmlType branchAnalysis;
    @XmlElement(namespace = "http://www.interpss.org/Schema/odm/2008")
    protected PtGenLossFactorXmlType genLossFactorAnalysis;
    @XmlElement(namespace = "http://www.interpss.org/Schema/odm/2008")
    protected PtAnalysisOutputXmlType outputOption;

    /**
     * Gets the value of the caseData property.
     * 
     * @return
     *     possible object is
     *     {@link PtCaseDataXmlType }
     *     
     */
    public PtCaseDataXmlType getCaseData() {
        return caseData;
    }

    /**
     * Sets the value of the caseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtCaseDataXmlType }
     *     
     */
    public void setCaseData(PtCaseDataXmlType value) {
        this.caseData = value;
    }

    /**
     * Gets the value of the aclfAnalysis property.
     * 
     * @return
     *     possible object is
     *     {@link PtAclfAnalysisXmlType }
     *     
     */
    public PtAclfAnalysisXmlType getAclfAnalysis() {
        return aclfAnalysis;
    }

    /**
     * Sets the value of the aclfAnalysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtAclfAnalysisXmlType }
     *     
     */
    public void setAclfAnalysis(PtAclfAnalysisXmlType value) {
        this.aclfAnalysis = value;
    }

    /**
     * Gets the value of the branchAnalysis property.
     * 
     * @return
     *     possible object is
     *     {@link PtBranchAnalysisXmlType }
     *     
     */
    public PtBranchAnalysisXmlType getBranchAnalysis() {
        return branchAnalysis;
    }

    /**
     * Sets the value of the branchAnalysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtBranchAnalysisXmlType }
     *     
     */
    public void setBranchAnalysis(PtBranchAnalysisXmlType value) {
        this.branchAnalysis = value;
    }

    /**
     * Gets the value of the genLossFactorAnalysis property.
     * 
     * @return
     *     possible object is
     *     {@link PtGenLossFactorXmlType }
     *     
     */
    public PtGenLossFactorXmlType getGenLossFactorAnalysis() {
        return genLossFactorAnalysis;
    }

    /**
     * Sets the value of the genLossFactorAnalysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtGenLossFactorXmlType }
     *     
     */
    public void setGenLossFactorAnalysis(PtGenLossFactorXmlType value) {
        this.genLossFactorAnalysis = value;
    }

    /**
     * Gets the value of the outputOption property.
     * 
     * @return
     *     possible object is
     *     {@link PtAnalysisOutputXmlType }
     *     
     */
    public PtAnalysisOutputXmlType getOutputOption() {
        return outputOption;
    }

    /**
     * Sets the value of the outputOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtAnalysisOutputXmlType }
     *     
     */
    public void setOutputOption(PtAnalysisOutputXmlType value) {
        this.outputOption = value;
    }

}
